# Generated by Django 2.2.11 on 2020-04-09 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type_name', models.CharField(max_length=100)),
                ('category_type_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_code', models.CharField(max_length=50)),
                ('supplier_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_type_name', models.CharField(max_length=100, unique=True)),
                ('warehouse_code', models.CharField(max_length=50, unique=True)),
                ('warehouse_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubUserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_userorder_number', models.CharField(max_length=50)),
                ('userorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_models.UserOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=500)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product_stock', models.IntegerField(default=0)),
                ('for_sale', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_models.Category')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_models.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_models.Product')),
                ('subuserorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_models.SubUserOrder')),
            ],
        ),
    ]
