# Generated by Django 2.2.11 on 2020-04-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0007_delete_proxytoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehouse_type_name',
            new_name='warehouse_name',
        ),
    ]
