# Generated by Django 2.2.11 on 2020-04-27 01:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app_models', '0008_auto_20200422_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullUserInfo',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
            ],
            options={
                'proxy': django.contrib.auth.models.User,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
