# Generated by Django 2.2.11 on 2020-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0009_auto_20200427_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='qq',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='weixin_openid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
