# Generated by Django 2.2.11 on 2020-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0010_auto_20200428_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('comments', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
