# Generated by Django 2.2.11 on 2020-05-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0014_feiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextratest',
            name='_pay_password',
            field=models.CharField(blank=True, db_column='pay_password', max_length=100),
        ),
    ]
