# Generated by Django 2.2.11 on 2020-05-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0016_auto_20200518_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='pay_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
