# Generated by Django 2.2.11 on 2020-05-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0017_auto_20200518_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextratest',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeiUser',
        ),
        migrations.DeleteModel(
            name='UserExtraTest',
        ),
    ]
