# Generated by Django 2.2.11 on 2020-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0019_sitelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='SiteLog',
            new_name='UserLog',
        ),
    ]
