# Generated by Django 2.2.11 on 2020-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0020_auto_20200524_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='ip',
            new_name='remote_addr',
        ),
        migrations.AddField(
            model_name='userlog',
            name='x_forwarded_for',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='x_real_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
